### ISSUE TITLE
Redirect legacy-etd to current etd site

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/ETD#3]
On the cascade server, implement a 301 redirect, so that all traffic coming to the legacy-etd site ends up on the homepage of the new etd site.

**Comment by mprefer** [comment]
301 redirect added:

[https://app.zenhub.com/files/64148105/1fcaf90c-4816-4d80-a148-23ac1f40fc03/download](https://app.zenhub.com/files/64148105/1fcaf90c-4816-4d80-a148-23ac1f40fc03/download)

**Comment by mprefer** [comment]
Won't take effect until after the DNS change,
